apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceAccountName: clo835
  volumes:
    - name: ebs
      persistentVolumeClaim:
        claimName: pvc-fp
  containers:
  - name: mysql
    image: 472108177454.dkr.ecr.us-east-1.amazonaws.com/db:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secrets-db
          key: password
    ports:
    - containerPort: 3306
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: ebs
